### ISSUE TITLE
Clean Up Temp Directories Prior to Repo Generation

### ISSUE THREAD

**Issue by amyschoen** [githubtraining/training-manual#244]
I was doing some script testing, and the clone failed in the middle due to a typo on my part.  Since it happened to fail in the middle of the repo creation process, I got the `Please grab a copy from https://github.com/githubtraining/github-games and upload it to your GHE instance.` error message as a false positive.  Should we do a check to see if the temp directory exists prior to cloning the temp repo and clean it up so we don't get misleading error messages?

As a side note, I noticed that the temp directory is hardcoded (at least in create-game-repo).  Should we have this set up as a global variable?  That would give people freedom to change it in their local copies in case they had a conflict with the directory we chose.

**Comment by brianamarie** [comment]
I think these are great ideas, @amyschoen! I am going to label this issue with "enhancement" and "help wanted". If anyone has bandwidth/interest in jumping in to make these changes, please go for it! ✨ 

cc @githubtraining/implementation-engineers @githubtraining/programs
