### ISSUE TITLE
Incorrect Default Branch in GHES

### ISSUE THREAD

**Issue by amyschoen** [githubtraining/training-manual#266]
When testing the changes in #261 against GHES, I noticed that the default branch can be variable since main isn't officially supported yet.  It ends up being the first branch in alphabetical order if master doesn't exist.  Even though this likely won't be an issue once main is officially supported by GHES, I do think it's a good addition since we'll always know what the default branch is.

This is a quick and easy fix.  We just need to make the call to set the default branch after repo creation since the API can't set it at creation and doesn't keep the same default branch as the template repo.

https://developer.github.com/v3/repos/#update-a-repository

**Comment by parkerbxyz** [comment]
> It ends up being the first branch in alphabetical order if master doesn't exist.

This was happening on github.com too. Thanks for the issue and PR to fix this @amyschoen! 😊
