### ISSUE TITLE
No PRs open in conflict practice repository

### ISSUE THREAD

**Issue by rwnfoo** [githubtraining/training-manual#287]
This only occured to 1 participant out of the 20 that I generated the conflict practice repo for, and no PRs were opened by `githubteacher`. I went ahead and open it manually, the repo link is here: https://github.com/githubschool/conflict-practice-art-vega-sage/pulls

**Comment by selkins13** [comment]
This happened to several of the participants in @AAugustine's class this morning.  There was at least one repo that it only created 1 of the 3 PRs as well.

**Comment by parkerbxyz** [comment]
I have not been able to reproduce this. 🤔

**Comment by selkins13** [comment]
This happened again to me today... here is the log.out
[log.out.zip](https://github.com/githubtraining/training-manual/files/6093118/log.out.zip)

**Comment by AAugustine** [comment]
In alpha order, it created PR's for 3 of 7 people, and then it created 1 PR for the next person, and zero PR's for the rest. Maybe it's a time out issue?

**Comment by parkerbxyz** [comment]
Unfortunately those logs won’t help until we get #294 merged. 🙁

**Comment by parkerbxyz** [comment]
Update: #294 has been merged. Now we should start to get the missing error logs in `script/log.out`.

@rwnfoo @selkins13 @AAugustine please do the following to help troubleshoot:

1. Delete the existing `script/log.out` file:

   ```sh
   rm script/log.out
   ```

1. Update your local scripts:

   ```sh
   git switch master && git pull
   ```

Next time your run into this problem, send me your new `script/log.out` file so I can investigate. 🕵️‍♂️ 

As a workaround while we get to the bottom of this, simply re-running the script should do the trick. Just be sure to answer `y` to the following prompt for the repos missing pull requests:

```sh
Is it OK to delete and recreate? [y/N]
```

You can just press <kbd>return</kbd> to accept the default answer of `N` (no) for those who already have all the pull requests.
