### ISSUE TITLE
Error messages not being displayed for repo generation

### ISSUE THREAD

**Issue by amyschoen** [githubtraining/training-manual#290]
I had a heck of a time attempting to troubleshoot repo generations mid class this morning.  It looks like one of the more recent changes that introduced the `-s` flag for silent mode also hides errors when they happen in the repo generation scripts.  Here's a snippet from the man page on curl:

```
-s, --silent
              Silent or quiet mode. Don't show progress meter or error
              messages.  Makes Curl mute. It will still output the data
              you ask for, potentially even to the terminal/stdout
              unless you redirect it.

              Use -S, --show-error in addition to this option to disable
              progress meter but still show error messages.

              See also -v, --verbose, --stderr and --no-progress-meter.
```

I'll get the scripts updated to add the `-S` flag, and then do a PR.  We'll want any errors that are occurring to be printed out in the logs.

CC @parkerbxyz

**Comment by parkerbxyz** [comment]
Thanks, @amyschoen! Good catch. I was also trying to troubleshoot an issue last week (#287) and couldn’t find any error output in the logs. I didn’t notice the errors were being silenced by the subtle difference of `-s` vs `-S`. 🤦‍♂️

**Comment by amyschoen** [comment]
We'll want both flags if I'm reading that man page correctly.  I'm doing to be doing some troubleshooting of why the scripts work in my test GHES instance and not in our regular one since they should be set up the same way.   That's why I volunteered to do a PR since I'll have the changes in my local version soon.
