### ISSUE TITLE
Refactor Curl

### ISSUE THREAD

**Issue by amyschoen** [githubtraining/training-manual#295]
We have nearly 100 curl calls in the training scripts, but there are only a few variants of the types of commands and flags used.  We should refactor the curl calls as functions in shared_functions to make it easier when we want to slightly tweak our curl commands in the future.

**Comment by parkerbxyz** [comment]
Another option would be to replace `curl` commands with [`gh api`](https://cli.github.com/manual/gh_api) or [`octo`](https://octo-cli.github.io/octo-cli/#/) commands. But this would introduce a new dependency to the scripts.

**Comment by amyschoen** [comment]
Thanks @parkerbxyz.  Your changes look pretty slick.  Teaching a class later this week, so I'll have to check out the updates after that.
