### ISSUE TITLE
Commenters not added as collaborators on class repo

### ISSUE THREAD

**Issue by amyschoen** [githubtraining/training-manual#311]
I ran into an error during class today when picking option 2 to add collabs and create files.  

```
What would you like to do? (Just the number please)
99: Exit
 0: Confirm setup
 1: Create a new caption-this class repository
 2: Add collabs and create files (also makes the repo private)
 3: Grade the day 1 repo
 4: Create conflict repos for each student
 5: Grade the conflict repos
 6: Create the github-games repos for each student
 7: Delete student repos for a specific class
 8: Grade client
2
What is the name of the day 1 repo?
AmyTest
running script/create-files

Adding collaborators...
./create-files: line 26: collaborators[*]: parameter null or not set
```

No commenters get added as collaborators and no files were generated.  I was able to work around it by manually adding every student in my class as a collaborator and then running option 2 again.  I think I've traced the issue down to the following two lines:

https://github.com/githubtraining/training-manual/blob/c2a42848a0f601105b8a31bc9b93f57059731c43/script/create-files#L222-L223

The two function calls are out of order.  `get_collaborators` assumes that the array of commenters is already populated.

I can fix this once I'm done with class tomorrow, but I don't have enough time to properly test the proposed changes until then.

**Comment by parkerbxyz** [comment]
> The two function calls are out of order. `get_collaborators` assumes that the array of commenters is already populated.

I’m not seeing where `get_collaborators` depends on the `commenters`. The `add_collaborators` function depends on it, but that shouldn’t affect `get_collaborators`.

**Comment by parkerbxyz** [comment]
> 2\. Make sure the instructor gets added as a collaborator on the repo if no one's there yet.

This is the approach I took in #342. Can you verify it works as expected?

**Comment by amyschoen** [comment]
Sure.  I'm upgrading httpie right now to test #342.  I'll add this to my test cases.
