### ISSUE TITLE
Detect default branch in class scripts

### ISSUE THREAD

**Issue by amyschoen** [githubtraining/training-manual#321]
I ran into the issue of PRs not being created for github-games in production even though the script ran fine when I tested on my test GHES instance.  The culprit ended up being the switch from master to main because my prod instance is still configured to use master.  To work around this in the future and prevent having to do manual changes when syncing .com to GHES, we should add detecting the default branch into create-practice-repos and use that instead of always hardcoding the base of the PR to main.

**Comment by parkerbxyz** [comment]
Looks like `git symbolic-ref refs/remotes/origin/HEAD` is still pointed to the old branch name, before it was renamed in that repo. You can fix that by running the following in that repo:

```sh
git remote set-head origin --auto
```

**Comment by parkerbxyz** [comment]
Maybe we can put it in the setup script so it can catch edge cases like the one you experienced without requiring extra troubleshooting.

**Comment by amyschoen** [comment]
I like that.
