### ISSUE TITLE
Environment by GitHub Codespaces to run teacher's scripts

### ISSUE THREAD

**Issue by dzeyelid** [githubtraining/training-manual#357]
I customized a Codespace environment for me to run `script/teach-class` script like my own PR below.
https://github.com/lefthandz-githubtraining/training-manual/pull/8

If you would like to use it in this repository too, I will be able to create a pull request here. What do you think?

**Comment by ppremk** [comment]
> If you would like to use it in this repository too, I will be able to create a pull request here. What do you think?

This is 💯 needed. Thank you @dzeyelid
