### ISSUE TITLE
teach-class script is not working

### ISSUE THREAD

**Issue by fatihdurgut** [githubtraining/training-manual#375]
As you can see the following image. I'm getting error when I chose step1 in the list although I completed the step 0

![image](https://user-images.githubusercontent.com/4159116/189523571-4aab4e2c-1ec7-4105-a2d3-08f2cd842954.png)

**Comment by amyschoen** [comment]
It looks like you might've had a copy/paste error when you set up your PAT.  I'd try running step 0 again to reset the config.  Otherwise, you can try taking a look at .trainingmanualrc in a text editor and just manually fix your PAT.  It's the line that starts with `export TEACHER_PAT=`.

**Comment by fatihdurgut** [comment]
Hello team,

I changed my PAT with a new one and also update the .trainingmanualrc with VSCode but still getting the following error.

![image](https://user-images.githubusercontent.com/4159116/190913236-802b58d5-8572-42a5-a43c-3d4ef02f43f0.png)

I'm running in elevated window

**Comment by fatihdurgut** [comment]
discard my previous comment. its working now
