### ISSUE TITLE
Cannot create new caption-this repository on Mac

### ISSUE THREAD

**Issue by ncsokas** [githubtraining/training-manual#422]
When running the ./teach-class script, I get similar error both on Linux and on Mac:

```
http: warning: HTTP 404 Not Found

http: warning: HTTP 404 Not Found

Updating contents of README.md... 
http: warning: HTTP 404 Not Found

jq: parse error: Invalid numeric literal at line 1, column 134
Done.
Updating contents of _config.yml... 
http: warning: HTTP 404 Not Found

jq: parse error: Invalid numeric literal at line 1, column 129
Done.
Branch protection rules updated.
Creating issue: Add collaborators to this repo... Done.
Creating project: Caption Contest... 
http: warning: HTTP 410 Gone

Done.
Creating project column: To do... 
http: warning: HTTP 404 Not Found


Done.
Creating project column: In progress... 
http: warning: HTTP 404 Not Found


Done.
Creating project column: Done... 
http: warning: HTTP 404 Not Found


Done.
Creating project card: ... 
http: warning: HTTP 404 Not Found
```

However, I don't get 

`jq: parse error: Invalid numeric literal at line 1, column 129`

on Linux and the repo seems to get created without issues (even though I still get the http warnings). 

On Mac, I only get an empty repository. 

On my Linux system, jq is version 1.6, on Mac 1.7. However, I was unable to downgrade. Not sure if that is the source of the problem. I checked https://github.com/githubtraining/training-manual/tree/main/script#local-configuration and there is no mention of required version.

**Comment by amyschoen** [comment]
Where is your source repo?  The scripts have .com and GHES support.  I don't think I ever circled back and merged back my local branches that add GHEC support.  I'm running jq-1.7.1 on a Mac, so I could try to repro.

**Comment by ncsokas** [comment]
Trying to create a repository in the organization https://github.com/github-developer-training-school
I already deleted the repo I was trying to create using Mac.
